<?php

$title = 'Connexion';
$this->headTitle($title);
echo $this->message;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('connexion', $this->url('utilisateur', array('action' => 'connexion')));
echo $this->form($form);
if(isset($this->erreur)){
    echo "<p class='alert alert-error'>" . $this->erreur . "</p>";
    if($this->erreur == "Email ou mot de passe incorrect"){
    	echo "<a class ='btn btn-info' href=".$this->url('utilisateur', array('action' => 'recup'))."> <i class ='icon-black icon-share-alt'></i> Mot de passe oublié</a>";
    }
}