<?php

$title = 'Inscription';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p id="infos"> 
<b>LA CRÉATION DE VOTRE COMPTE PERSONNEL EST GRATUITE</b>
<br>
Ce service vous permet de déposer vos propres annonces et vous permet de les gérer en toute simplicité. <br>
 Vous aurez également la possibilité de : <br>
- mettre les annonces qui vous intéressent en favoris afin de pouvoir les consulter aisément <br>
- enregistrer vos recherches afin d’être averti lorsqu’un produit correspondant est ajouté sur le site ! <br>
</p>


<?php
$form = $this->form;

$form->setAttribute('inscription', $this->url('utilisateur', array('action' => 'inscription')));//route dans module.config.php

echo $this->form($form);
