<?php

$title = 'Mes annonces';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if($pagination->getTotalItemCount() == 0)
        echo "Vous n'avez encore aucune annonce";
    else 
echo"
<table class=\"table\">
 <tr>
    <th>Date</th>
    <th>Photo</th>
    <th>Titre</th>
    <th>Prix</th>
    <th>Catégorie</th>
    <th>Département</th>
    <th>Actions</th>
</tr>"?>

<?php foreach ($pagination as $annonce) : ?>
<tr class="tableSurvol" onclick="document.location='<?php echo $this->url('annonce',array('action'=>'annonce', 'id' => $annonce->id_annonce));?>'">

    <td><?php echo $this->escapeHtml($annonce->date_modif);?></td>
    
    <td><img src="<?php
        if($meta[$annonce->id_annonce]['photo'])
            echo $this->basePath() . "/photos/" . $meta[$annonce->id_annonce]['photo']->id_photo ;
        else
            echo $this->basePath() . "/photos/no-image.png";
    ?>" class="miniature" /></td>
    <td><?php echo $this->escapeHtml($annonce->titre);?></td>
    <td><?php echo $this->escapeHtml($annonce->prix);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['categorie']->lib_cat);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['departement']->lib_dept);?></td>
    
    <td>
        <a href="<?php echo $this->url('annonce',
            array('action'=>'edit', 'id' => $annonce->id_annonce));?>">Modifier</a>
        <a href="<?php echo $this->url('annonce',
            array('action'=>'delete', 'id' => $annonce->id_annonce));?>">Supprimer</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->pagination, 'Sliding', 'partial/paginator.phtml', array('route' => 'utilisateur', 'action'=>'mesannonces','param' => $this->param)); ?>
