<?php

$title = 'Mes favoris';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if($pagination->getTotalItemCount() == 0)
        echo "<div class=\"alert alert-info\"> Vous n'avez encore aucun favori</div>";
    else 
echo "
<table class=\"table\">
 <tr>
    <th>Date</th>
    <th>Photo</th>
    <th>Titre</th>
    <th>Prix</th>
    <th>Catégorie</th>
    <th>Département</th>
    <th>Actions</th>
</tr>" ?>

<?php foreach ($pagination as $annonce) : ?>
<tr class="tableSurvol" onclick="document.location='<?php echo $this->url('annonce',array('action'=>'annonce', 'id' => $annonce->id_annonce));?>'">

    <td><?php echo $this->escapeHtml($annonce->date_modif);?></td>
    
    <td><img src="<?php
        if($meta[$annonce->id_annonce]['photo'])
            echo $this->basePath() . "/photos/" . $meta[$annonce->id_annonce]['photo']->id_photo ;
        else
            echo $this->basePath() . "/photos/no-image.png";
    ?>" class="miniature" /></td>
    <td>
         <a href="<?php echo $this->url('annonce',array('action'=>'annonce', 'id' => $annonce->id_annonce));?>">
            <?php echo $this->escapeHtml($annonce->titre);?>
        </a>
    </td>
    <td><?php echo $this->escapeHtml($annonce->prix);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['categorie']->lib_cat);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['departement']->lib_dept);?></td>
    <td>
    <a class="btn btn-danger" href="<?php echo $this->url('annonce', array('action'=>'deletefavoris', 'id' => $annonce->id_annonce));?>"><i class="icon-white icon-remove"></i> Supprimer ce favori</a>
    </td>
    
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->pagination, 'Sliding', 'partial/paginator.phtml', array('route' => 'utilisateur', 'action'=>'mesfavoris','param' => $this->param)); ?>

