<?php

$title = 'Mes recherches';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($pagination->getTotalItemCount() == 0)
        echo "<div class=\"alert alert-info\"> Vous n'avez encore aucune recherche enregistrée</div>";
    else 
echo"
<table class=\"table\">
 <tr>
    <th>Libellé</th>
    <th>Actions</th>
</tr>"?>

<?php foreach ($pagination as $recherche) : ?>
<tr>
    <td><?php echo $recherche['lib'];?></td>
    <td>
    <a class="btn btn-info" href="<?php echo $this->url('annonce', array_merge(array('action'=>'index'),$recherche['param']));?>"><i class="icon-black icon-eye-open"></i> Voir </a>
    <a class="btn btn-danger" href="<?php echo $this->url('utilisateur', array('action'=>'deleterecherche', 'id'=>$recherche['param']['id_rech']));?>"><i class="icon-black icon-remove"></i> Supprimer cette recherche</a>
    </td>
    
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->pagination, 'Sliding', 'partial/paginator.phtml', array('route' => 'utilisateur', 'action'=>'mesrecherches','param' => $this->param)); ?>
