<?php

$title = 'Contacter le vendeur';
$this->headTitle($title);
echo $this->message;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
	       <?php echo "<div class=\"alert alert-info\">
	        <b>Le mail est envoyé depuis notre adresse propre, 
	        si vous n'êtes pas inscrit ou non connecté pensez à mettre un moyen de contact 
	        pour que votre interlocuteur puisse vous joindre directement.</b><br/></div>"; ?>

<?php

	$form = $this->form;

	$form->setAttribute('message', $this->url('utilisateur', array('action' => 'message')));
	if(isset($this->erreur))
	{
    	echo "<p>" . $this->erreur . "</p>";
	}
	echo $this->form($form);