<?php

$title = 'Mon compte';
$this->headTitle($title);
/*echo $this->message;
var_dump($this->auth->getIdentity());*/
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<td>
    <?php echo "Nom : " . $this->escapeHtml($utilisateur->nom);?> <br>
    <?php echo "Prénom : " . $this->escapeHtml($utilisateur->prenom);?> <br>
    <?php echo "Pseudo : " . $this->escapeHtml($utilisateur->pseudo);?> <br>
    <?php echo "Adresse : " . $this->escapeHtml($utilisateur->adresse);?> <br>
    <?php echo "Code postal: " . $this->escapeHtml($utilisateur->cp);?> <br>
    <?php echo "Ville : " . $this->escapeHtml($utilisateur->ville);?> <br>
    <?php echo "Téléphone : " . $this->escapeHtml($utilisateur->tel);?> <br>
    <?php echo "Email : " . $this->escapeHtml($utilisateur->mail);?> <br>
    <?php echo "Statut : " . $this->escapeHtml($utilisateur->statut);?> <br>
    
</td>

<br>
<a href="<?php echo $this->url('utilisateur', array('action'=>'edit')) ;?>">Modifier vos informations</a>
<a href="<?php echo $this->url('utilisateur', array('action'=>'delete')) ;?>">Supprimer votre compte</a>

<!--rang 
mdp
description; 
id_dept;
-->