<?php

$title = 'Récupérer un nouveau mot de passe';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
	
<?php	echo "<div class=\"alert alert-info\">L'adresse mail doit être celle de votre compte. </div>"; ?>

<?php

$form = $this->form; 
$form->setAttribute('recup', $this->url('utilisateur', array('action' => 'recup')));
$form->prepare();

echo $this->form($form);

if(isset($this->erreur)){
    echo "<p class='alert alert-error'>" . $this->erreur . "</p>";
}