<?php

$title = 'Mes annonces';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
 <tr>
    <th>Titre</th>
    <th>Prix</th>
    <th>Catégorie</th>
    <th>Département</th>
    <th></th>
</tr>
<?php foreach ($annonces as $annonce) : ?>
<tr>
    <td><?php echo $this->escapeHtml($annonce->titre);?></td>
    <td><?php echo $this->escapeHtml($annonce->prix);?></td>
    <td><?php echo $this->escapeHtml($annonce->id_cat);?></td>
    <td><?php echo $this->escapeHtml($annonce->id_dept);?></td>

    <td>
        <a href="<?php echo $this->url('annonce',
            array('action'=>'edit', 'id' => $annonce->id_annonce));?>">Modifier</a>
        <a href="<?php echo $this->url('annonce',
            array('action'=>'delete', 'id' => $annonce->id_annonce));?>">Supprimer</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

