<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Annoncea')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo 'Annoncea' ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
						
							<!-- Début du menu. -->
							<!-- Le Home est accessible à tous et doit aboutir à la fonction de recherche. -->
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
							
							<!-- Les autres sections doivent être accessible aux membres connectés. -->
							<!-- Il est a noté qu'il faut remplacé echo $this->url('home') par le bon echo pour adapté le lien. -->
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Messagerie') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Favoris') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Mes Annonces') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('annonce', array('action'=>'add')); ?>"><?php echo $this->translate('Ajouter une Annonce') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Mon Compte') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Déconnexion') ?></a></li>
			
							<!-- Connexion est visible uniquement si la personne est déconnecté. -->
                            <li class="active"><a href="<?php echo $this->url('connexion') ?>"><?php echo 'Connexion' ?></a></li>
							
							<!-- Inscription est visible uniquement si la personne est déconnecté. -->
                            <li class="active"><a href="<?php echo $this->url('inscription') ?>"><?php echo 'Inscription' ?></a></li>
							
							<!-- Fin du menu. -->
					
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
