<?php
$title = 'Ajouter une annonce';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('annonce', array('action' => 'add')));
echo $this->form($form);

/*
voir les classes de Zend\Form\View\Helper
les appeler via les mots cles de Zend\Form\View\HeleperConfig
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_annonce'));
echo $this->formLabel($form->get('titre'));
echo $this->formText($form->get('titre'));
echo $this->formElementErrors($form->get('titre'));
echo $this->formLabel($form->get('descr'));
echo $this->formTextArea($form->get('descr'));
echo $this->formElementErrors($form->get('descr'));
echo $this->formLabel($form->get('type_annonce'));
echo $this->formInput($form->get('type_annonce'));
echo $this->formElementErrors($form->get('type_annonce'));
echo $this->formLabel($form->get('prix'));
echo $this->formInput($form->get('prix'));
echo $this->formElementErrors($form->get('prix'));
echo $this->formLabel($form->get('etat'));
echo $this->formInput($form->get('etat'));
echo $this->formElementErrors($form->get('etat'));
echo $this->formHidden($form->get('date_crea'));
echo $this->formHidden($form->get('date_modif'));
echo $this->formLabel($form->get('id_cat'));
echo $this->formInput($form->get('id_cat'));
echo $this->formElementErrors($form->get('id_cat'));
echo $this->formLabel($form->get('id_dept'));
echo $this->formInput($form->get('id_dept'));
echo $this->formElementErrors($form->get('id_dept'));
echo $this->formLabel($form->get('mail_auteur'));
echo $this->formInput($form->get('mail_auteur'));
echo $this->formElementErrors($form->get('mail_auteur'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
 * 
 */