<?php

$title = $annonce->titre; //recuperer le nom de l'objet 
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br>
<?php echo $this->escapeHtml($annonce->date_modif);?>  
<br>
<?php
        if($meta[$annonce->id_annonce]['photo']) {
            foreach($meta[$annonce->id_annonce]['photo'] as $photo) {
                echo "<img class=\"grande\" src=\"" . $this->basePath() . "/photos/" . $photo->id_photo . "\"/>"; 
            }
        }
        else
            echo "<img class=\"grande\" src=\"" . $this->basePath() . "/photos/no-image.png" . "\"/>";
?>
<br>
<?php echo "Prix : ";?>
<?php echo $this->escapeHtml($annonce->prix);?>  <?php echo "€";?>
<br>
<?php echo $this->escapeHtml($annonce->descr);?>   
<br>
<?php echo $this->escapeHtml($meta[$annonce->id_annonce]['departement']->lib_dept);?>   
<br>
<?php echo $this->escapeHtml($meta[$annonce->id_annonce]['categorie']->lib_cat);?>   
<br>

<a class="btn" href="<?php echo $this->url('annonce', array('action'=>'favoris', 'id' => $annonce->id_annonce));?>"> <i class="icon-black icon-star"></i> Mettre en favoris</a>

<a class="btn" href="<?php echo $this->url('utilisateur', array('action'=>'message', 'id' => $annonce->id_annonce));?>"> <i class="icon-black icon-envelope"></i> Contacter le vendeur</a>
</br>
</br>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52653629195e0ea4"></script>

<!-- AddThis Button END -->
<!--
<a href="<?php echo $this->url('annonce', array('action'=>'favoris', 'id' => $annonce->id_annonce));?>">Mettre en favoris</a>
<br>
<a href="<?php echo $this->url('utilisateur', array('action'=>'message', 'id' => $annonce->id_annonce));?>">Contacter le vendeur</a>
-->
