<?php

$title = 'Supprimer une annonce';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes-vous sûr de vouloir supprimer 
    '<?php echo $this->escapeHtml($annonce->titre); ?>' ? 
</p>
<?php
$url = $this->url('annonce', array(
    'action' => 'delete',
    'id'     => $this->id_annonce,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id_annonce" value="<?php echo (int) $annonce->id_annonce; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>