<?php

$title = 'Annonces';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                Faire une recherche
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse out">
            <div class="accordion-inner">
                <?php echo $this->form($form); ?>  
            </div>
        </div>
    </div>
</div>
<?php if($this->co)
    echo "<a class='btn' href=\""
    .$this->url($this->route, array_merge($this->param, array('action' => 'sauvegardeRecherche')))
    ."\">Enregistrer ma recherche</a>";?>
</br>
</br>


<?php if($pagination->getTotalItemCount() == 0)
        echo "<div class=\"alert alert-info\"> Aucune annonce ne correspond à votre recherche </div>";
    else 
echo"
<table class=\"table\">
<tr>
    <th>Date</th>
    <th>Photo</th>
    <th>Titre</th>
    <th>Prix</th>
    <th>Catégorie</th>
    <th>Département</th>
</tr>"?>

<?php foreach ($pagination as $annonce) : ?>
<tr class="tableSurvol" onclick="document.location='<?php echo $this->url('annonce',array('action'=>'annonce', 'id' => $annonce->id_annonce));?>'">
    <td><?php echo $this->escapeHtml($annonce->date_modif);?></td>
    <td><img src="<?php
        if($meta[$annonce->id_annonce]['photo'])
            echo $this->basePath() . "/photos/" . $meta[$annonce->id_annonce]['photo']->id_photo ;
        else
            echo $this->basePath() . "/photos/no-image.png";
    ?>" class="miniature" /></td>
    <td>
        <a href="<?php echo $this->url('annonce',array('action'=>'annonce', 'id' => $annonce->id_annonce));?>">
            <?php echo $this->escapeHtml($annonce->titre);?>
        </a>
    </td>
    <td><?php echo $this->escapeHtml($annonce->prix);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['categorie']->lib_cat);?></td>
    <td><?php echo $this->escapeHtml($meta[$annonce->id_annonce]['departement']->lib_dept);?></td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->pagination, 'Sliding', 'partial/paginator.phtml', array('route' => 'annonce', 'action'=>'index','param' => $this->param)); ?>